- nodeset:
    name: shake-factory-latest
    nodes:
      - name: container
        label: pod-haskell-cabal-f32

- job:
    name: shake-factory-hlint
    parent: hlint
    nodeset:
      nodes:
        - name: container
          label: pod-haskell-f32

- job:
    name: shake-factory-base
    abstract: true
    parent: shake-build
    nodeset: shake-factory-latest
    pre-run: playbooks/prepare.yaml
    vars:
      ghc_version: 8.6
    required-projects:
      - softwarefactory-project.io/software-factory/shake-factory

- job:
    name: shake-factory-test
    parent: shake-factory-base

- project:
    check: &jobs
      jobs:
        - cabal-test:
            vars:
              ghc_version: 8.6
            nodeset: shake-factory-latest
        - shake-factory-test
        - shake-factory-hlint
    gate: *jobs
