

- nodeset:
    name: shake-factory-latest
    nodes:
      - label: pod-haskell-cabal-f32
        name: container

- job:
    name: shake-factory-hlint
    nodeset:
      nodes:
        - label: pod-haskell-f32
          name: container
    parent: hlint

- job:
    abstract: true
    name: shake-factory-base
    nodeset: shake-factory-latest
    required-projects:
      - name: softwarefactory-project.io/software-factory/shake-factory
    roles:
      - zuul: zuul-jobs
    run: playbooks/shake.yaml
    vars:
      ghc_version: 8.6
      shake_target: ''

- job:
    name: shake-factory-test
    parent: shake-factory-base

- job:
    name: shake-factory-docs
    parent: shake-factory-base
    post-run:
      - playbooks/docs.yaml
    vars:
      docs_dir: build/docs
      shake_target: docs

- job:
    name: shake-factory-publish-docs
    nodeset: shake-factory-latest
    parent: docssf-publish
    post-run:
      - playbooks/docs.yaml
    required-projects:
      - name: softwarefactory-project.io/software-factory/shake-factory
    roles:
      - zuul: zuul-jobs
    run: playbooks/shake.yaml
    vars:
      docs_dir: build/docs
      ghc_version: 8.6
      shake_target: docs

- project:
    check:
      jobs:
        - shake-factory-hlint
        - shake-factory-test
        - shake-factory-docs
    gate:
      jobs:
        - shake-factory-hlint
        - shake-factory-test
        - shake-factory-docs
    post:
      jobs:
        - shake-factory-publish-docs
