- nodeset:
    name: shake-factory-latest
    nodes:
      - name: container
        label: pod-haskell-cabal-f32

- job:
    name: shake-factory-hlint
    parent: hlint
    nodeset:
      nodes:
        - name: container
          label: pod-haskell-f32

- job:
    name: shake-factory-base
    abstract: true
    parent: shake-build
    nodeset: shake-factory-latest
    pre-run: playbooks/prepare.yaml
    vars:
      ghc_version: 8.6
    required-projects:
      - softwarefactory-project.io/software-factory/shake-factory

- job:
    name: shake-factory-test
    parent: shake-factory-base

- job:
    name: shake-factory-docs
    parent: shake-factory-base
    post-run: playbooks/docs.yaml
    vars:
      shake_target: docs
      docs_dir: build/docs

# depends-on: https://softwarefactory-project.io/r/19187
# - job:
#     name: shake-factory-publish-docs
#     parent: shake-factory-docs
#     vars:
#       shake_target: docs

# - job:
#     name: shake-factory-publish-docs
#     parent: docssf-publish

- project:
    check: &jobs
      jobs:
        - cabal-test:
            vars:
              ghc_version: 8.6
            nodeset: shake-factory-latest
        - shake-factory-test
        - shake-factory-hlint
        - shake-factory-docs
    gate: *jobs
#    post:
#      jobs:
#        - shake-factory-publish-docs
