- hosts: all
  vars:
    project_dir: "{{ zuul.project.src_dir }}/{{ project_root|default('') }}"
  tasks:
    # Symlink does not work when npm link to parent file directory
    - name: Install node_modules
      command: "mv /usr/libexec/shake/node_modules {{ project_dir }}/node_modules"

    - name: Run npm install
      command: npm install --no-save
      args:
        chdir: "{{ project_dir }}"

    # Npm incorrectly install a nested node_modules for linked dependencies...
    - name: Remove linked node_modules
      shell: |
          for dep in $(grep '"file:\.\.\/' package.json | sed 's/.*:\.\.\/\(.*\)".*/\1/'); do
            rm -Rf ../$dep/node_modules/
          done
      args:
        chdir: "{{ project_dir }}"

    - name: Run npm test
      command: npm run test
      args:
        chdir: "{{ project_dir }}"
