- hosts: all
  vars:
    project_dir: "{{ zuul.project.src_dir }}/{{ project_root|default('') }}"
  tasks:
    # Symlink does not work when npm link to parent file directory
    - name: Install node_modules
      command: "mv /usr/libexec/shake/node_modules {{ project_dir }}/node_modules"

    - name: Run yarn install
      command: yarn install --no-lockfile --offline
      args:
        chdir: "{{ project_dir }}"

    - name: Run yarn test
      command: yarn test
      args:
        chdir: "{{ project_dir }}"
