- hosts: all
  vars:
    project_shakefile: "{{ zuul.project.src_dir }}/Shakefile.hs"
  tasks:
    - name: Install shake-factory
      shell: rm -Rf ~/.ghc && cabal install --lib lib:shake-factory dhall shake shake-dhall text
      args:
        chdir: "~/src/softwarefactory-project.io/software-factory/shake-factory"

    - name: Check if shakefile exist
      stat:
        path: "{{ project_shakefile }}"
      register: _shakefile

    - include_role:
        name: shake-build

    - name: Check for diff
      command: git diff
      args:
        chdir: "{{ zuul.project.src_dir }}"
      register: render_diff

    - name: Abort on diff
      when:
        - render_diff.stdout
        - not (diff_ignore_errors | default(false))
      failed_when: true
      debug:
        msg: |
          The repository index is modified after shake.
          Please run `shake {{ shake_target }}` before `git commit`

          The difference is:

          {{ git_diff.stdout }}
